# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/CSE100/Lab6/Lab6.cache/wt [current_project]
set_property parent.project_path D:/CSE100/Lab6/Lab6.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo d:/CSE100/Lab6/Lab6.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/Adder.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/SignChanger.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/StateLogic.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/StateMachine.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/countUD16L.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/countUD3L.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/countUD5L.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/counter4L.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/hex7seg.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/lab6_clks.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/m2_1x8.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/m4_1e.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/m8_1e.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/ring.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/selector.v
  D:/CSE100/Lab6/Lab6.srcs/sources_1/new/Lab6.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/CSE100/Lab6/Basys3_Master.xdc
set_property used_in_implementation false [get_files D:/CSE100/Lab6/Basys3_Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Lab6 -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Lab6.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Lab6_utilization_synth.rpt -pb Lab6_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
